name: payment-application-gateway

services:
  postgres:
    image: postgres
    container_name: payment-application-gateway-postgres
    environment:
      POSTGRES_DB: payment-application-gateway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - payment-application-gateway_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: payment-application-gateway-redis
    ports:
      - "6379:6379"
    volumes:
      - payment-application-gateway_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  payment-application-gateway_postgres_data:
  payment-application-gateway_redis_data:
